name: report to team
on:
  workflow_dispatch:
  push:
    branches:
      main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       - name: checkout
         uses: actions/checkout@v2
         
       - name: send to teams
         env: 
           WEBHOOK: ${{ secrets.WEBHOOK }}
         run: |
           trivy_output="$( echo 'HI Pruthvi')"
           json_payload="{\"text\": \"$trivy_output\"}"
           curl -X POST -H "Content-Type: application/json" --data-binary "$json_payload" $WEBHOOK
  
