name: report to team
on:
  workflow_dispatch:
  push:
    branches:
      main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       - name: checkout
         uses: actions/checkout@v2
         
       - name: create file
         run: |
           echo 'hello hi goodbye' > report.txt
           reportofme=$( cat report.txt )
         
       - name: send to teams
         env: 
           WEBHOOK: ${{ secrets.WEBHOOK }}
         run: |
           curl -X POST -H "Content-Type: text/plain" --data-binary "@reportofme" $WEBHOOK
  
