name: report to team
on:
  workflow_dispatch:
  push:
    branches:
      main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       - name: checkout
         uses: actions/checkout@v2
         
       - name: create file
         run: echo '{"summary":"John", "text":30, "car":null}' > report.json
         
       - name: send to teams
         env: 
           WEBHOOK: ${{ secrets.WEBHOOK }}
         run: |
           curl -X POST -H "Content-Type: application/json" --data-binary "@report.json" $WEBHOOK
  
